### ISSUE TITLE
Project Manager bugs

### ISSUE THREAD

**Issue by iLLiCiTiT** [pypeclub/OpenPype#1564]
## List of bugs in Project Manager
- [x] duplications of asset name does not work after save #1645
- [x] save seems to do nothing but it does #1645
- [x] add asset button on selected task will crash project manager #1646
- [x] task type changes are not saved properly (this was maybe fixed with #1645 too)

**Comment by BigRoy** [comment]
https://user-images.githubusercontent.com/2439881/120720487-729a0100-c4cc-11eb-8626-4b001cf6e1a5.mp4

3.0.0 tag

Hitting this bug where I can't create a sibling asset.

**Comment by BigRoy** [comment]
Visually it looks like you can change the Task type on existing saved tasks - but in practice you can't. It correctly does NOT propagate to the database - still it's confusing.


https://user-images.githubusercontent.com/2439881/120720784-f8b64780-c4cc-11eb-82a4-f1bc306aa238.mp4

**Comment by BigRoy** [comment]
Not sure how I'm having this happen - but it tends to get to a state where pressing `Save` does nothing. Where should I look to see what might be causing this?

https://user-images.githubusercontent.com/2439881/120721251-b93c2b00-c4cd-11eb-889f-e614153cdf6b.mp4

**Comment by BigRoy** [comment]
Selecting a Task and then clicking on Add Asset crashes the tool. :)

```
Traceback (most recent call last):
  File "S:\openpype\OpenPype\openpype\tools\project_manager\project_manager\window.py", line 189, in _on_add_asset
    self.hierarchy_view.add_asset()
  File "S:\openpype\OpenPype\openpype\tools\project_manager\project_manager\view.py", line 404, in add_asset
    return self._source_model.add_new_asset(parent_index)
  File "S:\openpype\OpenPype\openpype\tools\project_manager\project_manager\model.py", line 396, in add_new_asset
    result = self.add_item(new_child, item, new_row)
  File "S:\openpype\OpenPype\openpype\tools\project_manager\project_manager\model.py", line 459, in add_item
    result = self.add_items([item], parent, row)
  File "S:\openpype\OpenPype\openpype\tools\project_manager\project_manager\model.py", line 440, in add_items
    parent.add_child(item, row)
  File "S:\openpype\OpenPype\openpype\tools\project_manager\project_manager\model.py", line 1949, in add_child
    raise AssertionError("BUG: Can't add children to Task")
AssertionError: BUG: Can't add children to Task
```

The crash could be avoided by instead maybe popping up a pop-up using `sys.excepthook` that shows the error instead.

**Comment by BigRoy** [comment]
Double clicking (or pressing ENTER) on the name of existing assets (that are in database) allows you to rename the asset and save it to the database. Should renaming an asset be allowed? Is this correct behavior?

**Comment by iLLiCiTiT** [comment]
> Hitting this bug where I can't create a sibling asset.
and
> Not sure how I'm having this happen - but it tends to get to a state where pressing Save does nothing. Where should I look to see what might be causing this?

Fixed with: https://github.com/pypeclub/OpenPype/pull/1645

## Description
- save did not trigger refreshing of attributes holding data and asset duplications

**Comment by iLLiCiTiT** [comment]
> Double clicking (or pressing ENTER) on the name of existing assets (that are in database) allows you to rename the asset and save it to the database. Should renaming an asset be allowed? Is this correct behavior?

It won't allow to change asset name when has published content (at least one subset).

**Comment by iLLiCiTiT** [comment]
> Selecting a Task and then clicking on Add Asset crashes the tool. It takes down Pype Tray along with it.

Fixed with https://github.com/pypeclub/OpenPype/pull/1646

**Comment by iLLiCiTiT** [comment]
> Visually it looks like you can change the Task type on existing saved tasks - but in practice you can't. It INCORRECTLY does propagate the change to the database.

I think this was issue connected with #1645 Let me know if issue persist because it works on my side.

**Comment by iLLiCiTiT** [comment]
> By the way, I started posting multiple bugs here due to the top message saying "List of bugs" but I'm not sure whether it's alright I'm actually dropping all of these in one issue.

As it's in beta stage it is better to have it here. As you can see 2-3 issue were solved with 1 PR because were cause due to same bug cause by missing 2 lines.

**Comment by iLLiCiTiT** [comment]
Closing as it seems that all initial bugs are fixed and all other should be reported as separated issues.
