### ISSUE TITLE
Typed asset version dependencies

### ISSUE THREAD

**Issue by davidlatwe** [pypeclub/OpenPype#2092]
## Goal

As an artist/lead/developer, I would like to know the dependencies of a version (workfile/published output/etc.) so that I can make educated decisions without having to open or inspect the file/version in question.

## Use cases

* Knowing which versions were used in an output during a review.

* Ability to make better decisions in data transfer and cleanup tools.

## Details

Asset version dependencies should be typed (best configurable) to be able to represent different dependencies.

Example:

* Generative - No "active" dependency, the dependant was generated from the provider. Such as an image rendered from a Nuke script.

* Reference - The dependant actively uses the provider. Such as a rig referenced in a Maya scene or an image input into a Nuke script.

* Transitive: A indirect dependency, the dependent was generated from a provider that itself has a dependency on "the" provider. Such as the dependency from a rig to a model without references (where the direct dependency is "model">"workfile">"rig"),

* Member: The provider belongs to a "package" as a member.

Through typed dependencies, better decisions can be made. For ex. when transferring files only "reference" dependencies are actually needed etc..

### brainstorm in Miro

https://miro.com/app/board/o9J_lAB4oQ0=/

## Tasks
* [ ] publish incoming and outgoing links
* [ ] simple gui for displaying asset links
* [ ] simple gui for editing asset links

---
**Internal ticket: PYPE-1425**

[cuID:PYPE-1955]

**Comment by davidlatwe** [comment]
For the data that need to be published along with, I propose (after a short discuss with @mkolar) the following data model which will be written/updated in **version** type document's `data.link`.

```
# say in a pointcache version document's 'data.link'
{
    "involved": [
        ObjectId("layoutB"),
        ObjectId("renderS"),
    ],
    "inputs": [
        {id: ObjectId("rigB"), by: publish, type: generative}
        {id: ObjectId("animation-workfile"), by: publish, type: reference}
    ],
}
```

The `involved` field is for recording which product is involved, e.g. modelA-v001 may involved with renderX-v005.

The `inputs` fields is for links. From the Miro board, there are 4 types of links : generative, reference, transitive, member. For generative and reference type of links, they should be logged in document of course. But the other two, they seems indirect and can be calculated on the fly.

The `outputs` field is missing in above model, since they can be computed from other's `inputs`.

**Comment by mkolar** [comment]
Regarding `involved` I'm not sure how exactly to understand that one. Is it supposed to note if for example `modelMain v01` and `lookMain v01` are both used in something like `packageCharacterForRender`?

Group/Assembly/Package types of assets that are made of other things is a ticket we've been discussing for a while, but I feel that is outside the scope of this maybe?

**Comment by mkolar** [comment]
>The outputs field is missing in above model, since they can be computed from other's inputs.

yeah I think that is a good way to go about it. Question is whether having in and out (provided they are validated and each in has a corresponding out always) would speed up any browsing and querying for example.

**Comment by davidlatwe** [comment]
The `involved` field is mainly for reducing the database query when building the dependency network.

Say you want to build a network from `renderX v05`, simply fetch all version documents that has `renderX v05` Id in it's `data.link.involved` and sort out the connection locally. Without that field, I think you can only use aggregation to do that in one query.

> Question is whether having in and out (provided they are validated and each in has a corresponding out always) would speed up any browsing and querying for example.

I think having both in and out links in one document wouldn't help much, and may need to be extra care on maintaining the connection pair integrity between documents.

**Comment by davidlatwe** [comment]
Just an extra quick idea on how we can benefit from `involved` field. We could have *nodes* that doesn't have any links but still be counted in the network, like Notes which can be presented in GUI.

**Comment by davidlatwe** [comment]
> Group/Assembly/Package types of assets that are made of other things is a ticket we've been discussing for a while, but I feel that is outside the scope of this maybe?

:O I thought they should, don't they ?

**Comment by mkolar** [comment]
>:O I thought they should, don't they ?

Well that's the right question. I personally feel that they are closely related and `package` type of asset is dependent on this issue, but not the same. 

Package will most probably need more metadata then just knowing what is linked to it.

**Comment by mkolar** [comment]
This has been already solve conceptually and was improved on in v4 alpha already. What it needs now is to start creating those links from all hosts, but for that we'll need a bunch of new tickets to keep track of the work. This I believe can now be closed.
